In [5]:
import pandas as pd

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

print("Library Imported Successfully!")

Library Imported Successfully!

In [6]:
frequent_items = apriori(
    basket,
    min_support=0.01,
    use_colnames=True
)

frequent_items.head(10)

C:\Users\sampa\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support         itemsets
0  0.021386       (UHT-milk)
1  0.033950           (beef)
2  0.021787        (berries)
3  0.016574      (beverages)
4  0.045312   (bottled beer)
5  0.060683  (bottled water)
6  0.037626    (brown bread)
7  0.035220         (butter)
8  0.017577    (butter milk)
9  0.014369          (candy)

In [7]:
rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.3
)

rules = rules.sort_values(by="confidence", ascending=False)

rules[
    [
        "antecedents",
        "consequents",
        "support",
        "confidence",
        "lift"
    ]
].head(10)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [8]:
len(rules)

0

In [9]:
rules = association_rules(
    frequent_items,
    metric="confidence",
    min_threshold=0.1
)

rules = rules.sort_values(by="confidence", ascending=False)

rules[
    [
        "antecedents",
        "consequents",
        "support",
        "confidence",
        "lift"
    ]
].head(10)

          antecedents   consequents   support  confidence      lift
3            (yogurt)  (whole milk)  0.011161    0.129961  0.822940
1        (rolls/buns)  (whole milk)  0.013968    0.126974  0.804028
0  (other vegetables)  (whole milk)  0.014837    0.121511  0.769430
2              (soda)  (whole milk)  0.011629    0.119752  0.758296

In [10]:
def recommend(product_name):
    result = rules[
        rules["antecedents"].apply(
            lambda x: product_name in list(x)
        )
    ]

    return result[
        ["consequents", "confidence", "lift"]
    ].sort_values(
        by="confidence",
        ascending=False
    )

In [11]:
recommend("yogurt")

    consequents  confidence     lift
3  (whole milk)    0.129961  0.82294

In [12]:
strong_rules = rules[
    (rules["lift"] > 1) &
    (rules["confidence"] >= 0.1)
]

strong_rules[
    ["antecedents", "consequents", "support", "confidence", "lift"]
].sort_values(by="lift", ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [13]:
rules[
    ["antecedents", "consequents", "support", "confidence", "lift"]
].sort_values(by="confidence", ascending=False)

          antecedents   consequents   support  confidence      lift
3            (yogurt)  (whole milk)  0.011161    0.129961  0.822940
1        (rolls/buns)  (whole milk)  0.013968    0.126974  0.804028
0  (other vegetables)  (whole milk)  0.014837    0.121511  0.769430
2              (soda)  (whole milk)  0.011629    0.119752  0.758296